### PR TITLE
84 enable simple json parsing and use ov

### LINKED ISSUE #84: Enable simple json parsing and use overloaded strings to simplify (test) json.
see: https://ghc.gitlab.haskell.org/ghc/doc/users_guide/exts/overloaded_strings.html

### PR DESCRIPTION
**Pull request by JTeeuwissen**
resolves #84

### CODE REVIEW

**Comment by musicismyalibi** [comment]
Is there a reason that we create our own JSON parser instead of using an existing one like Aeson?

**Comment by JTeeuwissen** [comment]
> Is there a reason that we create our own JSON parser instead of using an existing one like Aeson?

Yes, although JsonLogic with Aeson is fine. Especially when already using Aeson. It can be a lot of overhead for a simpler project. This functionality is nice for demos without having to rely on a relatively big package.

**Comment by musicismyalibi** [comment]
I think it might be better to put the JSON parsing in a separate file.

**Comment by JTeeuwissen** [comment]
> I think it might be better to put the JSON parsing in a separate file.

I wanted to do so, but that would make it an orphan instance.
And moving just the parsing (not the instance) causes circular dependencies.

**Review by musicismyalibi — APPROVED** [review]

**Pull request merged**
